server:
  port: 10001
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    allow-bean-definition-overriding: true
app:
  thread:
    pool:
      core-size: 4
      max-size: 8
      queue-size: 1000
      keep-alive-time: 5